name: Build & Deploy Angular + Compodoc

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Install deps
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build Angular app
      - name: Build Angular
        run: |
          npm run build -- --configuration production --base-href /docu-web/


      # 5️⃣ Build Compodoc
      - name: Build Compodoc
        run: npm run compodoc:build

      # 6️⃣ Prepare GitHub Pages content (FIXED)
      - name: Prepare GitHub Pages content
        run: |
          mkdir gh-pages
          cp -r dist/my-angular-app/* gh-pages/
          mkdir gh-pages/docs
          cp -r docs/* gh-pages/docs/

      # 7️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages
